# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from group import Group
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.open()
    self.login(Group(user_name="user101", password="123456"))
    self.logout()

  def test_login_empty(self):
    self.open()
    self.login(Group(user_name="", password=""))
    self.logout()

  def logout(self):
    # logout
    self.driver.find_element(By.CSS_SELECTOR, "#mainLogoutButton .l-btn-text").click()

  def login(self, group):
    # login
    self.driver.find_element(By.ID, "edit-saas-login").send_keys(group.user_name)
    self.driver.find_element(By.ID, "edit-saas-pass").click()
    self.driver.find_element(By.ID, "edit-saas-pass").send_keys(group.password)
    self.driver.find_element(By.ID, "edit-submit").click()
    self.driver.find_element(By.CSS_SELECTOR, "#user_select_pos .l-btn-text").click()

  def open(self):
    # open
    self.driver.get("https://ioblik.com/")
  
